# Generated by Django 4.1.7 on 2023-10-25 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_auto_20231020_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salescreditnote1',
            name='scredit',
        ),
        migrations.DeleteModel(
            name='salescreditnote',
        ),
        migrations.DeleteModel(
            name='salescreditnote1',
        ),
    ]
