# Generated by Django 4.1.7 on 2023-10-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_salescreditnote_salescreditnote1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challanitem',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='challanitem',
            name='dl',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='e_waybill_item',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='e_waybill_item',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='e_waybills',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='e_waybills',
            name='cust',
        ),
        migrations.RemoveField(
            model_name='e_waybills',
            name='transportation',
        ),
        migrations.DeleteModel(
            name='challan',
        ),
        migrations.DeleteModel(
            name='challanitem',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.DeleteModel(
            name='e_waybill_item',
        ),
        migrations.DeleteModel(
            name='e_waybills',
        ),
    ]
