# Generated by Django 4.1.7 on 2023-10-30 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_salescreditnote_salescreditnote1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salescreditnote1',
            name='scredit',
        ),
        migrations.DeleteModel(
            name='salescreditnote',
        ),
        migrations.DeleteModel(
            name='salescreditnote1',
        ),
    ]
