# Generated by Django 4.1.7 on 2023-11-10 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_deletedcreditnotes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='salescreditnote1',
        ),
    ]
