# Generated by Django 4.1.7 on 2023-11-10 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_delete_salescreditnote1'),
    ]

    operations = [
        migrations.CreateModel(
            name='salescreditnote1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100, null=True)),
                ('hsn', models.CharField(max_length=100, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('tax', models.CharField(max_length=100, null=True)),
                ('discount', models.CharField(max_length=100, null=True)),
                ('total', models.CharField(max_length=100, null=True)),
                ('scredit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.salescreditnote')),
            ],
        ),
    ]
