# Generated by Django 4.1.7 on 2023-11-10 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_salescreditnote1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='salescreditnote1',
        ),
    ]
